ARG openssl_version=latest
FROM openssl_debug:${openssl_version}

ARG num_cores

COPY . /lib_src/cpprestsdk

RUN cd /lib_src/cpprestsdk \
  && mkdir build.debug \
  && cd build.debug \
  && cmake .. -DCMAKE_BUILD_TYPE=Debug -DWERROR=OFF \
  && make -j ${num_cores} \
  && make install \
  && cd / \
  && rm -rf /lib_src/cpprestsdk/build.debug \
  && ldconfig

CMD bash
